---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  VERSIONS: >-
    [
      {
        "NAME": "ansible",
        "VERSION": [
          "latest",
          "2.13"
        ],
        "KOPS": [
          "1.25",
          "1.24"
        ],
        "HELM": [
          "3.10",
          "3.9"
        ],
        "FLAVOUR": ["default"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      }
    ]
  FIELDS_BUILD: '["VERSION", "FLAVOUR", "ARCH"]'
  FIELDS_DEPLOY: '["VERSION", "FLAVOUR"]'


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      versions:
        description: "Stringified JSON of Versions definition."
        value: ${{ jobs.params.outputs.versions }}
      refs:
        description: "Stringified JSON of determined Refs (Only on scheduled runs)."
        value: ${{ jobs.params.outputs.refs }}
      fields_build:
        description: "Build fields to extract."
        value: ${{ jobs.params.outputs.fields_build }}
      fields_deploy:
        description: "Deploy fields to extract."
        value: ${{ jobs.params.outputs.fields_deploy }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
      refs: ${{ steps.set-refs.outputs.matrix }}
      fields_build: ${{ steps.set-fields.outputs.fields_build }}
      fields_deploy: ${{ steps.set-fields.outputs.fields_deploy }}

    steps:
      - name: "[Set-Output] Fields"
        id: set-fields
        run: |
          FIELDS_BUILD="$(  echo '${{ env.FIELDS_BUILD }}'  | jq -M -c )"
          FIELDS_DEPLOY="$( echo '${{ env.FIELDS_DEPLOY }}' | jq -M -c )"
          echo "fields_build=${FIELDS_BUILD}"   >> $GITHUB_OUTPUT
          echo "fields_deploy=${FIELDS_DEPLOY}" >> $GITHUB_OUTPUT

      - name: "[Set-Output] Versions"
        id: set-versions
        run: |
          VERSIONS="$( echo '${{ env.VERSIONS }}' | jq -M -c )"
          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT

      - name: "[Set-Output] Refs"
        id: set-refs
        uses: cytopia/git-ref-matrix-action@v0.1.12
        with:
          repository_default_branch: master
          branches: master
          num_latest_tags: 0
        if: github.event_name == 'schedule'

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Fields (build)'
          echo '--------------------'
          echo '${{ steps.set-fields.outputs.fields_build }}'
          echo

          echo 'Fields (deploy)'
          echo '--------------------'
          echo '${{ steps.set-fields.outputs.fields_deploy }}'
          echo

          echo 'Versions'
          echo '--------------------'
          echo '${{ steps.set-versions.outputs.versions }}'
          echo

          echo 'Refs'
          echo '--------------------'
          echo '${{ steps.set-refs.outputs.matrix }}'
          echo
