---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  VERSIONS: >-
    [
      {
        "NAME": "ansible",
        "VERSION": [
          "latest",
          "2.13"
        ],
        "KOPS": [
          "1.25",
          "1.24"
        ],
        "HELM": [
          "3.10",
          "3.9"
        ],
        "FLAVOUR": ["default"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      }
    ]
  FIELDS_BUILD: '[{"VERSION":"VERSION"}, {"ARCH":"ARCH"}]'
  FIELDS_DEPLOY: '[{"VERSION":"VERSION"}]'

  # Set Refs to build for scheduled jobs
  REFS: >-
    {
      "DEFAULT_BRANCH": "master",
      "BRANCHES": "master",
      "NUM_LATEST_TAGS": 0
    }


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      versions:
        description: "Stringified JSON of Versions definition."
        value: ${{ jobs.params.outputs.versions }}
      refs:
        description: "Stringified JSON of Refs definition."
        value: ${{ jobs.params.outputs.refs }}
      fields_build:
        description: "Stringified JSON of Build fields to extract."
        value: ${{ jobs.params.outputs.fields_build }}
      fields_deploy:
        description: "Stringified JSON of Deploy fields to extract."
        value: ${{ jobs.params.outputs.fields_deploy }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.set-json.outputs.versions }}
      refs: ${{ steps.set-json.outputs.refs }}
      fields_build: ${{ steps.set-json.outputs.fields_build }}
      fields_deploy: ${{ steps.set-json.outputs.fields_deploy }}

    steps:
      - name: "[Set-Output] JSON"
        id: set-json
        run: |
          VERSIONS="$(      echo '${{ env.VERSIONS }}'      | jq -M -c )"
          REFS="$(          echo '${{ env.REFS }}'          | jq -M -c )"
          FIELDS_BUILD="$(  echo '${{ env.FIELDS_BUILD }}'  | jq -M -c )"
          FIELDS_DEPLOY="$( echo '${{ env.FIELDS_DEPLOY }}' | jq -M -c )"

          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
          echo "refs=${REFS}"         >> $GITHUB_OUTPUT
          echo "fields_build=${FIELDS_BUILD}"   >> $GITHUB_OUTPUT
          echo "fields_deploy=${FIELDS_DEPLOY}" >> $GITHUB_OUTPUT

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Versions'
          echo '--------------------'
          echo '${{ steps.set-json.outputs.versions }}'
          echo

          echo 'Refs'
          echo '--------------------'
          echo '${{ steps.set-json.outputs.refs }}'
          echo

          echo 'Fields (build)'
          echo '--------------------'
          echo '${{ steps.set-json.outputs.fields_build }}'
          echo

          echo 'Fields (deploy)'
          echo '--------------------'
          echo '${{ steps.set-json.outputs.fields_deploy }}'
          echo
