---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: test


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on: [push, pull_request, pull_request_target]


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------------------------------------------
      # Echo Context
      # ------------------------------------------------------------
      - name: Context
        run: |
          echo "actor:      ${{ github.actor }}"
          echo "base_ref:   ${{ github.base_ref }}"
          echo "head_ref:   ${{ github.head_ref }}"
          echo "ref:        ${{ github.ref }}"
          echo "ref_type:   ${{ github.ref_type }}"
          echo "event_name: ${{ github.event_name }}"

      - name: Test
        run: |
          git show
